version: "3.7"
networks:
  my-network:
    driver: bridge
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "springboot_app"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - my-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - my-network

  user-service:
      build: User_Service/UserService/
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/springboot_app
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      restart: always
      networks:
        - my-network
      depends_on:
        - postgres
  address-service:
      build: Address_Service/AddressService/
      restart: always
      networks:
        - my-network
  transaction-service:
      build: Transaction_Service/TransactionService/
      restart: always
      networks:
        - my-network
