server:
  port : 8080

spring:
  datasource:
    url: postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: false
        format-sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#  h2:
#    console:
#      enabled: false