version: "3.7"
networks:
  my-network:
    driver: bridge
services:
  postgres:
    container_name: container_pg
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - my-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - my-network

  user-service:
      build: .
      ports:
        - "8080:8080"
      restart: always
      networks:
        - my-network
  address-service:
      build: .
      restart: always
      networks:
        - my-network
  transaction-service:
      build: .
      restart: always
      networks:
        - my-network
